const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const money=n=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(Number(n)||0);

async function health(){try{const r=await fetch("/api/health"),d=await r.json();$("health").textContent=d.captapiConfigured?"API configured":"API key missing";$("health").style.color=d.captapiConfigured?"#65e59a":"#ff7d88"}catch{$("health").textContent="Server offline"}} 
function render(items){$("results").innerHTML=items.length?items.map(x=>`<article class="result"><a href="${esc(x.url)}" target="_blank" rel="noopener">${x.image?`<img src="${esc(x.image)}" alt="">`:`<div style="height:165px;background:#0b1016"></div>`}<div class="result-body"><div class="result-title">${esc(x.title)}</div><div class="result-price">${esc(x.price)}</div><div class="meta">${esc(x.location||x.source)}</div>${x.condition?`<div class="meta">Condition: ${esc(x.condition)}</div>`:""}</div></a></article>`).join(""):`<div class="empty">No listings returned. Try a wider radius or another search.</div>`}
$("form").addEventListener("submit",async e=>{e.preventDefault();$("error").classList.add("hidden");$("loading").classList.remove("hidden");const p=new URLSearchParams({q:$("q").value,maxPrice:$("price").value,location:$("location").value,radius:$("radius").value,source:$("source").value});try{const r=await fetch("/api/search?"+p),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||"Search failed");$("title").textContent=`${d.query.q} around ${d.query.location}`;$("count").textContent=`${d.listings.length} listings`;render(d.listings);if(d.message){$("error").textContent=d.message;$("error").classList.remove("hidden")}}catch(e){$("error").textContent=e.message;$("error").classList.remove("hidden");render([]);$("count").textContent="0 listings"}finally{$("loading").classList.add("hidden")}});

function profit(){const n=Number($("scrap").value||0)+Number($("cats").value||0)-Number($("buy").value||0)-Number($("costs").value||0);$("profit").textContent=money(n)}
["buy","scrap","cats","costs"].forEach(id=>$(id).addEventListener("input",profit));health();profit();
